import type {
  Client,
  Fournisseur,
  Vehicule,
  Dossier,
  Facture,
  Utilisateur,
  Expedition,
  DossierDocument,
  TimelineEntry,
  Offre,
  PaiementClient,
  Cout,
  Tache,
  Note,
} from '@/types';

// ─── Clients ─────────────────────────────────────────────────────────

export const clients: Client[] = [
  {
    id: 'cli-001',
    nom: 'Amrani',
    prenom: 'Brahim',
    telephone: '+213 555 123 456',
    email: 'b.amrani@email.dz',
    numero_passeport: 'C-2849201',
    adresse: 'Alger, Hydra',
    date_inscription: '2026-01-15',
    nombre_dossiers: 2,
  },
  {
    id: 'cli-002',
    nom: 'Benali',
    prenom: 'Karim',
    telephone: '+213 555 234 567',
    email: 'k.benali@email.dz',
    numero_passeport: 'C-3921847',
    adresse: 'Oran, Bir El Djir',
    date_inscription: '2026-02-20',
    nombre_dossiers: 1,
  },
  {
    id: 'cli-003',
    nom: 'Zerhouni',
    prenom: 'Nadia',
    telephone: '+213 555 345 678',
    email: 'n.zerhouni@email.dz',
    numero_passeport: 'C-1029384',
    adresse: 'Constantine, Centre',
    date_inscription: '2026-03-10',
    nombre_dossiers: 1,
  },
  {
    id: 'cli-004',
    nom: 'Messaoudi',
    prenom: 'Youcef',
    telephone: '+213 555 456 789',
    email: 'y.messaoudi@email.dz',
    numero_passeport: 'C-5738291',
    adresse: 'Annaba, Sidi Amar',
    date_inscription: '2026-04-05',
    nombre_dossiers: 1,
  },
  {
    id: 'cli-005',
    nom: 'Bouzid',
    prenom: 'Amina',
    telephone: '+213 555 567 890',
    email: 'a.bouzid@email.dz',
    numero_passeport: 'C-8472019',
    adresse: 'Tlemcen, Centre',
    date_inscription: '2026-05-12',
    nombre_dossiers: 1,
  },
  {
    id: 'cli-006',
    nom: 'Khelifi',
    prenom: 'Mohamed',
    telephone: '+213 555 678 901',
    email: 'm.khelifi@email.dz',
    numero_passeport: 'C-6192837',
    adresse: 'Sétif, Centre',
    date_inscription: '2026-06-01',
    nombre_dossiers: 1,
  },
];

// ─── Fournisseurs ────────────────────────────────────────────────────

export const fournisseurs: Fournisseur[] = [
  {
    id: 'four-001',
    nom: 'Sino Auto Ltd',
    pays: 'Chine',
    ville: 'Shanghai',
    contact: 'Li Wei',
    email: 'liwei@sinoauto.cn',
    telephone: '+86 21 5555 1234',
    nombre_vehicules: 12,
  },
  {
    id: 'four-002',
    nom: 'Dragon Motors Co.',
    pays: 'Chine',
    ville: 'Guangzhou',
    contact: 'Zhang Min',
    email: 'zhang.min@dragonmotors.cn',
    telephone: '+86 20 6666 5678',
    nombre_vehicules: 8,
  },
  {
    id: 'four-003',
    nom: 'Pacific Vehicle Trading',
    pays: 'Chine',
    ville: 'Shenzhen',
    contact: 'Chen Hao',
    email: 'chen@pacificvt.cn',
    telephone: '+86 755 8888 9012',
    nombre_vehicules: 15,
  },
  {
    id: 'four-004',
    nom: 'Golden Star Auto Export',
    pays: 'Chine',
    ville: 'Beijing',
    contact: 'Wang Jun',
    email: 'wangjun@goldenstar.cn',
    telephone: '+86 10 7777 3456',
    nombre_vehicules: 6,
  },
  {
    id: 'four-005',
    nom: 'Yangtze Auto Group',
    pays: 'Chine',
    ville: 'Chongqing',
    contact: 'Liu Fang',
    email: 'liu.fang@yangtzeauto.cn',
    telephone: '+86 23 4444 7890',
    nombre_vehicules: 10,
  },
  {
    id: 'four-006',
    nom: 'Eastern Horizon Motors',
    pays: 'Chine',
    ville: 'Tianjin',
    contact: 'Xu Peng',
    email: 'xupeng@ehorizon.cn',
    telephone: '+86 22 3333 2345',
    nombre_vehicules: 4,
  },
];

// ─── Véhicules ───────────────────────────────────────────────────────

export const vehicules: Vehicule[] = [
  {
    id: 'veh-001',
    vin: 'WBAFG01010L191234',
    marque: 'BMW',
    modele: 'X5',
    annee: 2023,
    couleur: 'Noir',
    prix_achat_cny: 350000,
    prix_achat_dzd: 6500000,
    fournisseur_id: 'four-001',
    fournisseur_nom: 'Sino Auto Ltd',
    source: 'offre',
    statut: 'en_mer',
    photos: [],
    date_ajout: '2026-06-15',
  },
  {
    id: 'veh-002',
    vin: 'LSVAU2A89NE012345',
    marque: 'Audi',
    modele: 'Q7',
    annee: 2024,
    couleur: 'Blanc',
    prix_achat_cny: 420000,
    prix_achat_dzd: 7800000,
    fournisseur_id: 'four-002',
    fournisseur_nom: 'Dragon Motors Co.',
    source: 'corapide',
    statut: 'disponible',
    photos: [],
    date_ajout: '2026-05-20',
  },
  {
    id: 'veh-003',
    vin: 'WDC2539632A891011',
    marque: 'Mercedes-Benz',
    modele: 'GLE 350',
    annee: 2024,
    couleur: 'Gris',
    prix_achat_cny: 480000,
    prix_achat_dzd: 8900000,
    fournisseur_id: 'four-001',
    fournisseur_nom: 'Sino Auto Ltd',
    source: 'offre',
    statut: 'reserve',
    photos: [],
    date_ajout: '2026-04-10',
  },
  {
    id: 'veh-004',
    vin: 'JTDKN3DU5A5678901',
    marque: 'Toyota',
    modele: 'Land Cruiser',
    annee: 2023,
    couleur: 'Blanc',
    prix_achat_cny: 550000,
    prix_achat_dzd: 10200000,
    fournisseur_id: 'four-003',
    fournisseur_nom: 'Pacific Vehicle Trading',
    source: 'offre',
    statut: 'en_douane',
    photos: [],
    date_ajout: '2026-03-25',
  },
  {
    id: 'veh-005',
    vin: 'SALGS2RE5LA234567',
    marque: 'Range Rover',
    modele: 'Sport',
    annee: 2024,
    couleur: 'Vert',
    prix_achat_cny: 620000,
    prix_achat_dzd: 11500000,
    fournisseur_id: 'four-004',
    fournisseur_nom: 'Golden Star Auto Export',
    source: 'offre',
    statut: 'livre',
    photos: [],
    date_ajout: '2026-02-18',
  },
  {
    id: 'veh-006',
    vin: 'WP0AA2A98KS345678',
    marque: 'Porsche',
    modele: 'Cayenne',
    annee: 2024,
    couleur: 'Rouge',
    prix_achat_cny: 750000,
    prix_achat_dzd: 13900000,
    fournisseur_id: 'four-005',
    fournisseur_nom: 'Yangtze Auto Group',
    source: 'offre',
    statut: 'vendu',
    photos: [],
    date_ajout: '2026-01-10',
  },
  {
    id: 'veh-007',
    vin: 'JTDBT923612034567',
    marque: 'Toyota',
    modele: 'Prius',
    annee: 2021,
    couleur: 'Argent',
    prix_achat_cny: 0,
    prix_achat_dzd: 0,
    fournisseur_id: '',
    fournisseur_nom: 'Externe — client',
    source: 'external',
    statut: 'disponible',
    photos: [],
    date_ajout: '2026-07-10',
  },
  {
    id: 'veh-008',
    vin: 'WVGZZZ5NZLW345678',
    marque: 'Volkswagen',
    modele: 'Touareg',
    annee: 2022,
    couleur: 'Bleu',
    prix_achat_cny: 0,
    prix_achat_dzd: 0,
    fournisseur_id: '',
    fournisseur_nom: 'Externe — client',
    source: 'external',
    statut: 'reserve',
    photos: [],
    date_ajout: '2026-07-22',
  },
  {
    id: 'veh-009',
    vin: 'KMHJ2514TKU456789',
    marque: 'Hyundai',
    modele: 'Tucson',
    annee: 2023,
    couleur: 'Gris',
    prix_achat_cny: 260000,
    prix_achat_dzd: 4800000,
    fournisseur_id: 'four-006',
    fournisseur_nom: 'Eastern Horizon Motors',
    source: 'corapide',
    statut: 'en_mer',
    photos: [],
    date_ajout: '2026-08-01',
  },
  {
    id: 'veh-010',
    vin: 'WDC2530482K678901',
    marque: 'Mercedes-Benz',
    modele: 'GLC 300',
    annee: 2022,
    couleur: 'Noir',
    prix_achat_cny: 0,
    prix_achat_dzd: 0,
    fournisseur_id: '',
    fournisseur_nom: 'Externe — client',
    source: 'external',
    statut: 'disponible',
    photos: [],
    date_ajout: '2026-08-05',
  },
];

// ─── Offres Chine ────────────────────────────────────────────────────

export const offres: Offre[] = [
  {
    id: 'off-001',
    marque: 'BMW',
    modele: 'X5',
    annee: 2023,
    type: 'occasion',
    kilometrage: 42000,
    photos: [],
    fournisseur_nom: 'Sino Auto Ltd',
    prix_cif: 48500,
    prix_ddp: 55200,
    devise: 'USD',
    disponibilite: 'En stock Shanghai',
    statut: 'disponible',
  },
  {
    id: 'off-002',
    marque: 'Mercedes-Benz',
    modele: 'GLE 350',
    annee: 2024,
    type: 'occasion',
    kilometrage: 15000,
    photos: [],
    fournisseur_nom: 'Sino Auto Ltd',
    prix_cif: 58500,
    prix_ddp: 66500,
    devise: 'USD',
    disponibilite: 'En stock Shanghai',
    statut: 'reservee',
  },
  {
    id: 'off-003',
    marque: 'Audi',
    modele: 'Q7',
    annee: 2024,
    type: 'occasion',
    kilometrage: 28000,
    photos: [],
    fournisseur_nom: 'Dragon Motors Co.',
    prix_cif: 51200,
    prix_ddp: 58200,
    devise: 'USD',
    disponibilite: 'En stock Guangzhou',
    statut: 'disponible',
  },
  {
    id: 'off-004',
    marque: 'Toyota',
    modele: 'Land Cruiser',
    annee: 2023,
    type: 'occasion',
    kilometrage: 35000,
    photos: [],
    fournisseur_nom: 'Pacific Vehicle Trading',
    prix_cif: 62500,
    prix_ddp: 71200,
    devise: 'USD',
    disponibilite: 'Disponible sous 2 semaines',
    statut: 'disponible',
  },
  {
    id: 'off-005',
    marque: 'Range Rover',
    modele: 'Sport',
    annee: 2024,
    type: 'occasion',
    kilometrage: 12000,
    photos: [],
    fournisseur_nom: 'Golden Star Auto Export',
    prix_cif: 69800,
    prix_ddp: 79200,
    devise: 'USD',
    disponibilite: 'En stock Beijing',
    statut: 'vendue',
  },
  {
    id: 'off-006',
    marque: 'Porsche',
    modele: 'Cayenne',
    annee: 2024,
    type: 'occasion',
    kilometrage: 9000,
    photos: [],
    fournisseur_nom: 'Yangtze Auto Group',
    prix_cif: 84200,
    prix_ddp: 94500,
    devise: 'USD',
    disponibilite: 'En stock Chongqing',
    statut: 'disponible',
  },
  {
    id: 'off-007',
    marque: 'Hyundai',
    modele: 'Tucson',
    annee: 2023,
    type: 'neuf',
    kilometrage: 0,
    photos: [],
    fournisseur_nom: 'Eastern Horizon Motors',
    prix_cif: 32500,
    prix_ddp: 38200,
    devise: 'USD',
    disponibilite: 'Neuf — sous 3 semaines',
    statut: 'disponible',
  },
  {
    id: 'off-008',
    marque: 'BMW',
    modele: 'X6',
    annee: 2022,
    type: 'occasion',
    kilometrage: 51000,
    photos: [],
    fournisseur_nom: 'Sino Auto Ltd',
    prix_cif: 46500,
    prix_ddp: 53400,
    devise: 'USD',
    disponibilite: 'Expirée',
    statut: 'expiree',
  },
];

// ─── Factures ────────────────────────────────────────────────────────

export const factures: Facture[] = [
  {
    id: 'fac-001',
    reference: 'FAC-2026-081',
    dossier_id: 'dos-001',
    dossier_reference: 'CA-2026-0032',
    libelle: 'Acompte',
    montant_dzd: 1600000,
    date: '2026-08-01',
    statut: 'payee',
  },
  {
    id: 'fac-002',
    reference: 'FAC-2026-102',
    dossier_id: 'dos-001',
    dossier_reference: 'CA-2026-0032',
    libelle: 'Solde partiel',
    montant_dzd: 800000,
    date: '2026-08-10',
    statut: 'en_attente',
  },
  {
    id: 'fac-003',
    reference: 'FAC-2026-115',
    dossier_id: 'dos-001',
    dossier_reference: 'CA-2026-0032',
    libelle: 'Frais douane',
    montant_dzd: 400000,
    date: '2026-08-15',
    statut: 'en_retard',
  },
  {
    id: 'fac-004',
    reference: 'FAC-2026-043',
    dossier_id: 'dos-002',
    dossier_reference: 'CA-2026-0018',
    libelle: 'Acompte',
    montant_dzd: 2000000,
    date: '2026-05-15',
    statut: 'payee',
  },
  {
    id: 'fac-005',
    reference: 'FAC-2026-044',
    dossier_id: 'dos-002',
    dossier_reference: 'CA-2026-0018',
    libelle: 'Solde final',
    montant_dzd: 5800000,
    date: '2026-06-20',
    statut: 'payee',
  },
  {
    id: 'fac-006',
    reference: 'FAC-2026-120',
    dossier_id: 'dos-003',
    dossier_reference: 'CA-2026-0045',
    libelle: 'Acompte',
    montant_dzd: 3000000,
    date: '2026-07-01',
    statut: 'payee',
  },
  {
    id: 'fac-007',
    reference: 'FAC-2026-150',
    dossier_id: 'dos-004',
    dossier_reference: 'CA-2026-0051',
    libelle: 'Acompte',
    montant_dzd: 2500000,
    date: '2026-07-20',
    statut: 'en_attente',
  },
];

// ─── Documents (checklist) ───────────────────────────────────────────

export const documentsDossier001: DossierDocument[] = [
  {
    id: 'doc-001',
    dossier_id: 'dos-001',
    type: 'id_client',
    nom: 'Passeport_client.pdf',
    taille: '2.1 Mo',
    url: '#',
    upload_par: 'S. Mansouri',
    date: '2026-07-28',
    version: 1,
    statut: 'recu',
    notes: '',
  },
  {
    id: 'doc-002',
    dossier_id: 'dos-001',
    type: 'contrat',
    nom: 'Contrat_signe.pdf',
    taille: '1.2 Mo',
    url: '#',
    upload_par: 'S. Mansouri',
    date: '2026-08-01',
    version: 2,
    statut: 'valide',
    notes: 'Version finale signée par le client',
  },
  {
    id: 'doc-003',
    dossier_id: 'dos-001',
    type: 'pi_fournisseur',
    nom: 'Proforma_SinoAuto.pdf',
    taille: '0.6 Mo',
    url: '#',
    upload_par: 'W. Liu',
    date: '2026-07-20',
    version: 1,
    statut: 'recu',
    notes: '',
  },
  {
    id: 'doc-004',
    dossier_id: 'dos-001',
    type: 'preuve_paiement',
    nom: 'Preuve_acompte_fournisseur.pdf',
    taille: '0.4 Mo',
    url: '#',
    upload_par: 'F. Boukhris',
    date: '2026-07-22',
    version: 1,
    statut: 'recu',
    notes: '',
  },
  {
    id: 'doc-005',
    dossier_id: 'dos-001',
    type: 'documents_vehicule',
    nom: 'Documents_vehicule_X5.pdf',
    taille: '3.0 Mo',
    url: '#',
    upload_par: 'W. Liu',
    date: '2026-07-23',
    version: 1,
    statut: 'en_attente',
    notes: 'COC en attente du fournisseur',
  },
  {
    id: 'doc-006',
    dossier_id: 'dos-001',
    type: 'rapport_inspection',
    nom: 'Inspection_X5.pdf',
    taille: '1.8 Mo',
    url: '#',
    upload_par: 'W. Liu',
    date: '2026-07-24',
    version: 1,
    statut: 'recu',
    notes: '',
  },
  {
    id: 'doc-007',
    dossier_id: 'dos-001',
    type: 'bl_draft',
    nom: 'BL_draft_MSCU1187.pdf',
    taille: '0.5 Mo',
    url: '#',
    upload_par: 'K. Rahmani',
    date: '2026-08-05',
    version: 1,
    statut: 'recu',
    notes: '',
  },
  {
    id: 'doc-008',
    dossier_id: 'dos-001',
    type: 'bl_final',
    nom: 'BL_final_MSCU1187.pdf',
    taille: '0.5 Mo',
    url: '#',
    upload_par: 'K. Rahmani',
    date: '',
    version: 1,
    statut: 'manquant',
    notes: 'À récupérer à destination',
  },
];

// ─── Timeline (audit trail) ──────────────────────────────────────────

export const timelineDossier001: TimelineEntry[] = [
  {
    id: 'tim-001',
    dossier_id: 'dos-001',
    date: '2026-07-15T10:30:00',
    utilisateur: 'A. Djelloul',
    action: 'Dossier créé',
    type: 'systeme',
    details: 'Dossier ouvert suite à la demande du client B. Amrani',
  },
  {
    id: 'tim-002',
    dossier_id: 'dos-001',
    date: '2026-07-16T14:00:00',
    utilisateur: 'A. Djelloul',
    action: 'Statut → Offre sélectionnée',
    type: 'statut',
    details: 'BMW X5 2023 sélectionné (off-001, Sino Auto Ltd)',
  },
  {
    id: 'tim-003',
    dossier_id: 'dos-001',
    date: '2026-07-20T09:15:00',
    utilisateur: 'W. Liu',
    action: 'Véhicule associé',
    type: 'systeme',
    details: 'BMW X5 2023 (VIN: WBAFG01010L191234) rattaché au dossier',
  },
  {
    id: 'tim-004',
    dossier_id: 'dos-001',
    date: '2026-07-22T11:00:00',
    utilisateur: 'F. Boukhris',
    action: 'Statut → Paiement fournisseur',
    type: 'statut',
    details: 'Acompte fournisseur de 20 000 $ payé à Sino Auto Ltd',
  },
  {
    id: 'tim-005',
    dossier_id: 'dos-001',
    date: '2026-07-24T16:30:00',
    utilisateur: 'W. Liu',
    action: 'Inspection validée',
    type: 'tache',
    details: 'Inspection du véhicule effectuée — rapport reçu',
  },
  {
    id: 'tim-006',
    dossier_id: 'dos-001',
    date: '2026-07-28T10:00:00',
    utilisateur: 'K. Rahmani',
    action: 'Statut → En transit',
    type: 'statut',
    details: 'Véhicule chargé sur MSC ZONDA, conteneur MSCU-1187-4',
  },
  {
    id: 'tim-007',
    dossier_id: 'dos-001',
    date: '2026-08-01T10:00:00',
    utilisateur: 'S. Mansouri',
    action: 'Contrat signé',
    type: 'document',
    details: 'Contrat signé par le client, acompte de 1 600 000 DA reçu',
  },
  {
    id: 'tim-008',
    dossier_id: 'dos-001',
    date: '2026-08-10T09:00:00',
    utilisateur: 'F. Boukhris',
    action: 'Paiement partiel client reçu',
    type: 'paiement',
    details: '800 000 DA reçus — solde restant à percevoir avant livraison',
  },
];

// ─── Finance & collaboration (dos-001) ───────────────────────────────

export const paiementsDossier001: PaiementClient[] = [
  {
    id: 'pay-001',
    dossier_id: 'dos-001',
    type: 'acompte',
    montant: 1600000,
    devise: 'DZD',
    taux_change: 0.0077,
    date: '2026-08-01',
    methode: 'Virement bancaire',
  },
  {
    id: 'pay-002',
    dossier_id: 'dos-001',
    type: 'partiel',
    montant: 800000,
    devise: 'DZD',
    taux_change: 0.0077,
    date: '2026-08-10',
    methode: 'Virement bancaire',
  },
  {
    id: 'pay-003',
    dossier_id: 'dos-001',
    type: 'final',
    montant: 30000,
    devise: 'USD',
    taux_change: null,
    date: '',
    methode: 'Espèces agence',
  },
];

export const coutsDossier001: Cout[] = [
  {
    id: 'cout-001',
    dossier_id: 'dos-001',
    type: 'achat_vehicule',
    montant: 45000,
    devise: 'USD',
    taux_change: null,
    date: '2026-07-25',
    fournisseur_id: 'four-001',
  },
  {
    id: 'cout-002',
    dossier_id: 'dos-001',
    type: 'inspection',
    montant: 200,
    devise: 'USD',
    taux_change: null,
    date: '2026-07-24',
    fournisseur_id: null,
  },
  {
    id: 'cout-003',
    dossier_id: 'dos-001',
    type: 'shipping',
    montant: 1700,
    devise: 'USD',
    taux_change: null,
    date: '2026-07-27',
    fournisseur_id: null,
  },
  {
    id: 'cout-004',
    dossier_id: 'dos-001',
    type: 'port',
    montant: 300,
    devise: 'USD',
    taux_change: null,
    date: '',
    fournisseur_id: null,
  },
];

export const tachesDossier001: Tache[] = [
  {
    id: 'tac-001',
    dossier_id: 'dos-001',
    titre: 'Récupérer le BL final à destination',
    assigne_a: 'K. Rahmani',
    departement: 'Shipping',
    date_echeance: '2026-08-25',
    priorite: 'haute',
    statut: 'en_cours',
    description: 'Récupérer le BL original auprès de la compagnie maritime.',
    commentaires: 'Prévenir le client dès réception.',
  },
  {
    id: 'tac-002',
    dossier_id: 'dos-001',
    titre: 'Récupérer le COC du véhicule',
    assigne_a: 'W. Liu',
    departement: 'Ops Chine',
    date_echeance: '2026-08-20',
    priorite: 'normale',
    statut: 'a_faire',
    description: 'Relancer Sino Auto Ltd pour le certificat de conformité.',
    commentaires: '',
  },
  {
    id: 'tac-003',
    dossier_id: 'dos-001',
    titre: 'Préparer la facture solde final',
    assigne_a: 'F. Boukhris',
    departement: 'Finance',
    date_echeance: '2026-08-28',
    priorite: 'normale',
    statut: 'a_faire',
    description: 'Émettre la facture du solde (30 000 $) avant livraison.',
    commentaires: '',
  },
];

export const notesDossier001: Note[] = [
  {
    id: 'not-001',
    dossier_id: 'dos-001',
    auteur: 'S. Mansouri',
    date: '2026-08-02T15:00:00',
    contenu:
      'Client très pressé : souhaite une livraison dès que possible après arrivée du bateau. Prévoir livraison à Hydra.',
  },
  {
    id: 'not-002',
    dossier_id: 'dos-001',
    auteur: 'W. Liu',
    date: '2026-08-05T09:30:00',
    contenu:
      'Le fournisseur a confirmé que le COC sera envoyé par voie électronique sous 10 jours.',
  },
];

// ─── Dossiers secondaires (données partagées) ────────────────────────

export const documentsDossier002: DossierDocument[] = [
  {
    id: 'doc-101',
    dossier_id: 'dos-002',
    type: 'id_client',
    nom: 'Passeport_client.pdf',
    taille: '1.9 Mo',
    url: '#',
    upload_par: 'S. Mansouri',
    date: '2026-05-12',
    version: 1,
    statut: 'recu',
    notes: '',
  },
  {
    id: 'doc-102',
    dossier_id: 'dos-002',
    type: 'contrat',
    nom: 'Contrat_signe.pdf',
    taille: '1.3 Mo',
    url: '#',
    upload_par: 'S. Mansouri',
    date: '2026-05-15',
    version: 1,
    statut: 'valide',
    notes: '',
  },
  {
    id: 'doc-103',
    dossier_id: 'dos-002',
    type: 'pi_fournisseur',
    nom: 'Proforma_GoldenStar.pdf',
    taille: '0.7 Mo',
    url: '#',
    upload_par: 'W. Liu',
    date: '2026-05-16',
    version: 1,
    statut: 'recu',
    notes: '',
  },
  {
    id: 'doc-104',
    dossier_id: 'dos-002',
    type: 'rapport_inspection',
    nom: 'Inspection_RRSport.pdf',
    taille: '2.0 Mo',
    url: '#',
    upload_par: 'W. Liu',
    date: '2026-05-20',
    version: 1,
    statut: 'recu',
    notes: '',
  },
  {
    id: 'doc-105',
    dossier_id: 'dos-002',
    type: 'bl_final',
    nom: 'BL_final_EGLV2938.pdf',
    taille: '0.5 Mo',
    url: '#',
    upload_par: 'K. Rahmani',
    date: '2026-06-12',
    version: 1,
    statut: 'valide',
    notes: '',
  },
  {
    id: 'doc-106',
    dossier_id: 'dos-002',
    type: 'document_livraison',
    nom: 'PV_livraison.pdf',
    taille: '0.9 Mo',
    url: '#',
    upload_par: 'S. Mansouri',
    date: '2026-07-12',
    version: 1,
    statut: 'recu',
    notes: '',
  },
];

export const timelineDossier002: TimelineEntry[] = [
  {
    id: 'tim-101',
    dossier_id: 'dos-002',
    date: '2026-05-10T09:00:00',
    utilisateur: 'A. Djelloul',
    action: 'Dossier créé',
    type: 'systeme',
    details: 'Dossier ouvert pour K. Benali (Range Rover Sport)',
  },
  {
    id: 'tim-102',
    dossier_id: 'dos-002',
    date: '2026-05-15T10:00:00',
    utilisateur: 'S. Mansouri',
    action: 'Contrat signé',
    type: 'document',
    details: 'Acompte de 2 000 000 DA reçu',
  },
  {
    id: 'tim-103',
    dossier_id: 'dos-002',
    date: '2026-05-20T16:00:00',
    utilisateur: 'W. Liu',
    action: 'Inspection validée',
    type: 'tache',
    details: 'Véhicule inspecté à Beijing — conforme',
  },
  {
    id: 'tim-104',
    dossier_id: 'dos-002',
    date: '2026-06-20T11:00:00',
    utilisateur: 'F. Boukhris',
    action: 'Paiement fournisseur complété',
    type: 'paiement',
    details: 'Solde fournisseur de 31 000 $ réglé',
  },
  {
    id: 'tim-105',
    dossier_id: 'dos-002',
    date: '2026-07-12T09:30:00',
    utilisateur: 'S. Mansouri',
    action: 'Statut → Clôturé',
    type: 'statut',
    details: 'Véhicule livré à Oran, dossier clôturé',
  },
];

export const documentsDossier005: DossierDocument[] = [
  {
    id: 'doc-201',
    dossier_id: 'dos-005',
    type: 'id_client',
    nom: 'Passeport_client.pdf',
    taille: '1.8 Mo',
    url: '#',
    upload_par: 'S. Mansouri',
    date: '2026-03-05',
    version: 1,
    statut: 'recu',
    notes: '',
  },
  {
    id: 'doc-202',
    dossier_id: 'dos-005',
    type: 'contrat',
    nom: 'Contrat_signe.pdf',
    taille: '1.2 Mo',
    url: '#',
    upload_par: 'S. Mansouri',
    date: '2026-03-08',
    version: 1,
    statut: 'valide',
    notes: '',
  },
  {
    id: 'doc-203',
    dossier_id: 'dos-005',
    type: 'bl_final',
    nom: 'BL_final_MSKU3219.pdf',
    taille: '0.5 Mo',
    url: '#',
    upload_par: 'K. Rahmani',
    date: '2026-05-10',
    version: 1,
    statut: 'valide',
    notes: '',
  },
  {
    id: 'doc-204',
    dossier_id: 'dos-005',
    type: 'document_livraison',
    nom: 'PV_livraison.pdf',
    taille: '0.8 Mo',
    url: '#',
    upload_par: 'S. Mansouri',
    date: '2026-06-30',
    version: 1,
    statut: 'recu',
    notes: '',
  },
];

export const timelineDossier005: TimelineEntry[] = [
  {
    id: 'tim-201',
    dossier_id: 'dos-005',
    date: '2026-03-01T09:00:00',
    utilisateur: 'A. Djelloul',
    action: 'Dossier créé',
    type: 'systeme',
    details: 'Dossier ouvert pour A. Bouzid (Porsche Cayenne)',
  },
  {
    id: 'tim-202',
    dossier_id: 'dos-005',
    date: '2026-03-08T10:00:00',
    utilisateur: 'S. Mansouri',
    action: 'Contrat signé',
    type: 'document',
    details: 'Acompte de 5 000 000 DA reçu',
  },
  {
    id: 'tim-203',
    dossier_id: 'dos-005',
    date: '2026-06-05T14:00:00',
    utilisateur: 'F. Boukhris',
    action: 'Statut → Documents remis',
    type: 'statut',
    details: 'Documents remis au client après dédouanement',
  },
];

export const documentsDossier009: DossierDocument[] = [
  {
    id: 'doc-301',
    dossier_id: 'dos-009',
    type: 'id_client',
    nom: 'Passeport_client.pdf',
    taille: '2.0 Mo',
    url: '#',
    upload_par: 'S. Mansouri',
    date: '2026-06-16',
    version: 1,
    statut: 'recu',
    notes: '',
  },
  {
    id: 'doc-302',
    dossier_id: 'dos-009',
    type: 'contrat',
    nom: 'Contrat_shipping.pdf',
    taille: '1.1 Mo',
    url: '#',
    upload_par: 'S. Mansouri',
    date: '2026-06-18',
    version: 1,
    statut: 'valide',
    notes: '',
  },
  {
    id: 'doc-303',
    dossier_id: 'dos-009',
    type: 'bl_final',
    nom: 'BL_final.pdf',
    taille: '0.5 Mo',
    url: '#',
    upload_par: 'K. Rahmani',
    date: '2026-07-05',
    version: 1,
    statut: 'valide',
    notes: '',
  },
  {
    id: 'doc-304',
    dossier_id: 'dos-009',
    type: 'document_livraison',
    nom: 'PV_livraison.pdf',
    taille: '0.7 Mo',
    url: '#',
    upload_par: 'S. Mansouri',
    date: '2026-07-30',
    version: 1,
    statut: 'recu',
    notes: '',
  },
];

export const timelineDossier009: TimelineEntry[] = [
  {
    id: 'tim-301',
    dossier_id: 'dos-009',
    date: '2026-06-15T09:00:00',
    utilisateur: 'A. Djelloul',
    action: 'Dossier créé',
    type: 'systeme',
    details: 'Expédition seule pour N. Zerhouni (Volkswagen Touareg)',
  },
  {
    id: 'tim-302',
    dossier_id: 'dos-009',
    date: '2026-06-18T10:00:00',
    utilisateur: 'S. Mansouri',
    action: 'Contrat signé',
    type: 'document',
    details: 'Devis shipping accepté, acompte reçu',
  },
  {
    id: 'tim-303',
    dossier_id: 'dos-009',
    date: '2026-07-30T12:00:00',
    utilisateur: 'K. Rahmani',
    action: 'Statut → Service terminé',
    type: 'statut',
    details: 'Véhicule livré au client, service terminé',
  },
];

// ─── Expéditions ─────────────────────────────────────────────────────

export const expeditions: Expedition[] = [
  {
    id: 'exp-001',
    numero_conteneur: 'MSCU-1187-4',
    navire: 'MSC ZONDA',
    numero_bl: 'MSCUGB123456',
    port_depart: 'Shanghai, CN',
    port_arrivee: 'Alger, DZ',
    etd: '2026-07-28',
    eta: '2026-08-22',
    statut: 'en_mer',
    nombre_vehicules: 3,
    dossier_ids: ['dos-001', 'dos-003'],
    vehicle_ids: ['veh-001', 'veh-002', 'veh-003'],
  },
  {
    id: 'exp-002',
    numero_conteneur: 'CMAU-4521-7',
    navire: 'CMA CGM MARCO POLO',
    numero_bl: 'CMAUGZ789012',
    port_depart: 'Guangzhou, CN',
    port_arrivee: 'Alger, DZ',
    etd: '2026-08-05',
    eta: '2026-09-01',
    statut: 'en_mer',
    nombre_vehicules: 2,
    dossier_ids: ['dos-004'],
    vehicle_ids: ['veh-004'],
  },
  {
    id: 'exp-003',
    numero_conteneur: 'EGLV-2938-1',
    navire: 'EVERGREEN EVER ACE',
    numero_bl: 'EGLVSH345678',
    port_depart: 'Shanghai, CN',
    port_arrivee: 'Oran, DZ',
    etd: '2026-06-10',
    eta: '2026-07-05',
    statut: 'arrivee',
    nombre_vehicules: 4,
    dossier_ids: ['dos-002'],
    vehicle_ids: ['veh-005'],
  },
  {
    id: 'exp-004',
    numero_conteneur: 'HLXU-7654-3',
    navire: 'HAPAG-LLOYD BERLIN EXPRESS',
    numero_bl: 'HLXUBJ901234',
    port_depart: 'Tianjin, CN',
    port_arrivee: 'Alger, DZ',
    etd: '2026-08-20',
    eta: '2026-09-15',
    statut: 'planifiee',
    nombre_vehicules: 1,
    dossier_ids: ['dos-006'],
    vehicle_ids: ['veh-009'],
  },
  {
    id: 'exp-005',
    numero_conteneur: 'MSKU-3219-8',
    navire: 'MAERSK SEALAND',
    numero_bl: 'MSKUSZ567890',
    port_depart: 'Shenzhen, CN',
    port_arrivee: 'Alger, DZ',
    etd: '2026-05-01',
    eta: '2026-05-28',
    statut: 'dedouanee',
    nombre_vehicules: 2,
    dossier_ids: ['dos-005'],
    vehicle_ids: ['veh-006'],
  },
  {
    id: 'exp-006',
    numero_conteneur: 'TCLU-8472-5',
    navire: 'COSCO SHIPPING ALPS',
    numero_bl: 'TCLUCQ234567',
    port_depart: 'Chongqing, CN',
    port_arrivee: 'Alger, DZ',
    etd: '2026-09-01',
    eta: '2026-09-28',
    statut: 'planifiee',
    nombre_vehicules: 3,
    dossier_ids: [],
    vehicle_ids: ['veh-002', 'veh-009'],
  },
];

// ─── Utilisateurs ────────────────────────────────────────────────────

export const utilisateurs: Utilisateur[] = [
  {
    id: 'usr-001',
    nom: 'Djelloul',
    prenom: 'Ahmed',
    email: 'a.djelloul@carimport.dz',
    role: 'super_admin',
    actif: true,
    date_creation: '2025-12-01',
    avatar_initials: 'AD',
  },
  {
    id: 'usr-002',
    nom: 'Mansouri',
    prenom: 'Sara',
    email: 's.mansouri@carimport.dz',
    role: 'sales_algerie',
    actif: true,
    date_creation: '2026-01-10',
    avatar_initials: 'SM',
  },
  {
    id: 'usr-003',
    nom: 'Liu',
    prenom: 'Wei',
    email: 'w.liu@carimport.dz',
    role: 'operations_chine',
    actif: true,
    date_creation: '2026-01-15',
    avatar_initials: 'LW',
  },
  {
    id: 'usr-004',
    nom: 'Boukhris',
    prenom: 'Fatima',
    email: 'f.boukhris@carimport.dz',
    role: 'finance',
    actif: true,
    date_creation: '2026-02-01',
    avatar_initials: 'FB',
  },
  {
    id: 'usr-005',
    nom: 'Rahmani',
    prenom: 'Kamel',
    email: 'k.rahmani@carimport.dz',
    role: 'shipping',
    actif: true,
    date_creation: '2026-02-15',
    avatar_initials: 'KR',
  },
  {
    id: 'usr-006',
    nom: 'Taleb',
    prenom: 'Rachid',
    email: 'r.taleb@carimport.dz',
    role: 'dedouanement',
    actif: false,
    date_creation: '2026-03-01',
    avatar_initials: 'RT',
  },
];

// ─── Dossiers (full detail) ─────────────────────────────────────────

export const dossiers: Dossier[] = [
  {
    id: 'dos-001',
    reference: 'CA-2026-0032',
    type: 'cif',
    client_id: 'cli-001',
    client_nom: 'B. Amrani',
    fournisseur_nom: 'Sino Auto Ltd',
    statut: 'en_transit',
    origine: 'client',
    date_creation: '2026-07-15',
    date_mise_a_jour: '2026-08-10',
    responsable_chine_id: 'usr-003',
    responsable_algerie_id: 'usr-002',
    offre_id: 'off-001',
    supplier_id: 'four-001',
    contrat_statut: 'signe',
    contrat_date: '2026-08-01',
    client: clients[0],
    vehicles: [vehicules[0]],
    purchase: {
      id: 'PUR-2026-0012',
      dossier_id: 'dos-001',
      vehicle_id: 'veh-001',
      supplier_id: 'four-001',
      montant: 45000,
      devise: 'USD',
      acompte_fournisseur: 20000,
      solde_fournisseur: 25000,
      statut_paiement: 'partiel',
      date_echeance: '2026-08-25',
      conditions_negociees: 'Paiement 50% à la commande, solde avant BL.',
      responsable_chine_id: 'usr-003',
      documents: ['Proforma_SinoAuto.pdf', 'Preuve_acompte_fournisseur.pdf'],
    },
    paiements_client: paiementsDossier001,
    couts: coutsDossier001,
    expedition: {
      numero_conteneur: 'MSCU-1187-4',
      navire: 'MSC ZONDA',
      numero_bl: 'MSCUGB123456',
      port_depart: 'Shanghai, CN',
      port_arrivee: 'Alger, DZ',
      etd: '2026-07-28',
      eta: '2026-08-22',
      statut: 'en_mer',
    },
    douane: undefined,
    documents: documentsDossier001,
    taches: tachesDossier001,
    timeline: timelineDossier001,
    notes: notesDossier001,
  },
  {
    id: 'dos-002',
    reference: 'CA-2026-0018',
    type: 'cif',
    client_id: 'cli-002',
    client_nom: 'K. Benali',
    fournisseur_nom: 'Golden Star Auto Export',
    statut: 'cloture',
    origine: 'client',
    date_creation: '2026-05-10',
    date_mise_a_jour: '2026-07-15',
    responsable_chine_id: 'usr-003',
    responsable_algerie_id: 'usr-002',
    offre_id: 'off-005',
    supplier_id: 'four-004',
    contrat_statut: 'signe',
    contrat_date: '2026-05-15',
    client: clients[1],
    vehicles: [vehicules[4]],
    purchase: {
      id: 'PUR-2026-0005',
      dossier_id: 'dos-002',
      vehicle_id: 'veh-005',
      supplier_id: 'four-004',
      montant: 56000,
      devise: 'USD',
      acompte_fournisseur: 25000,
      solde_fournisseur: 31000,
      statut_paiement: 'paye',
      date_echeance: null,
      conditions_negociees: 'Acompte 25 000 $, solde avant chargement.',
      responsable_chine_id: 'usr-003',
      documents: ['Proforma_GoldenStar.pdf'],
    },
    paiements_client: [
      {
        id: 'pay-101',
        dossier_id: 'dos-002',
        type: 'acompte',
        montant: 2000000,
        devise: 'DZD',
        taux_change: 0.0077,
        date: '2026-05-15',
        methode: 'Virement bancaire',
      },
      {
        id: 'pay-102',
        dossier_id: 'dos-002',
        type: 'final',
        montant: 5800000,
        devise: 'DZD',
        taux_change: 0.0077,
        date: '2026-06-20',
        methode: 'Virement bancaire',
      },
    ],
    couts: [
      {
        id: 'cout-101',
        dossier_id: 'dos-002',
        type: 'achat_vehicule',
        montant: 56000,
        devise: 'USD',
        taux_change: null,
        date: '2026-05-25',
        fournisseur_id: 'four-004',
      },
      {
        id: 'cout-102',
        dossier_id: 'dos-002',
        type: 'shipping',
        montant: 1900,
        devise: 'USD',
        taux_change: null,
        date: '2026-06-05',
        fournisseur_id: null,
      },
      {
        id: 'cout-103',
        dossier_id: 'dos-002',
        type: 'port',
        montant: 320,
        devise: 'USD',
        taux_change: null,
        date: '2026-07-06',
        fournisseur_id: null,
      },
    ],
    expedition: {
      numero_conteneur: 'EGLV-2938-1',
      navire: 'EVERGREEN EVER ACE',
      numero_bl: 'EGLVSH345678',
      port_depart: 'Shanghai, CN',
      port_arrivee: 'Oran, DZ',
      etd: '2026-06-10',
      eta: '2026-07-05',
      statut: 'arrivee',
    },
    douane: {
      numero_declaration: 'DD-2026-4521',
      date_declaration: '2026-07-08',
      bureau_douane: 'Bureau Oran Port',
      valeur_declaree_dzd: 11500000,
      droits_douane_dzd: 2300000,
      tva_dzd: 1380000,
      total_frais_dzd: 3680000,
      statut: 'validee',
      date_dedouanement: '2026-07-12',
    },
    documents: documentsDossier002,
    taches: [
      {
        id: 'tac-101',
        dossier_id: 'dos-002',
        titre: 'Archiver le dossier',
        assigne_a: 'A. Djelloul',
        departement: 'Admin',
        date_echeance: '2026-07-20',
        priorite: 'basse',
        statut: 'terminee',
        description: 'Clôturer le dossier et archiver les documents.',
        commentaires: '',
      },
    ],
    timeline: timelineDossier002,
    notes: [],
  },
  {
    id: 'dos-003',
    reference: 'CA-2026-0045',
    type: 'cif',
    client_id: 'cli-003',
    client_nom: 'N. Zerhouni',
    fournisseur_nom: 'Sino Auto Ltd',
    statut: 'achat_confirme',
    origine: 'client',
    date_creation: '2026-06-25',
    date_mise_a_jour: '2026-08-01',
    responsable_chine_id: 'usr-003',
    responsable_algerie_id: 'usr-002',
    offre_id: 'off-002',
    supplier_id: 'four-001',
    contrat_statut: 'signe',
    contrat_date: '2026-07-01',
    client: clients[2],
    vehicles: [vehicules[2], vehicules[1]],
    purchase: {
      id: 'PUR-2026-0020',
      dossier_id: 'dos-003',
      vehicle_id: 'veh-003',
      supplier_id: 'four-001',
      montant: 110000,
      devise: 'USD',
      acompte_fournisseur: 30000,
      solde_fournisseur: 80000,
      statut_paiement: 'partiel',
      date_echeance: '2026-08-30',
      conditions_negociees: 'Acompte 30 000 $, solde avant BL. Deux véhicules.',
      responsable_chine_id: 'usr-003',
      documents: ['Proforma_SinoAuto_2veh.pdf'],
    },
    paiements_client: [
      {
        id: 'pay-201',
        dossier_id: 'dos-003',
        type: 'acompte',
        montant: 3000000,
        devise: 'DZD',
        taux_change: 0.0077,
        date: '2026-07-01',
        methode: 'Virement bancaire',
      },
    ],
    couts: [
      {
        id: 'cout-201',
        dossier_id: 'dos-003',
        type: 'acompte_fournisseur',
        montant: 30000,
        devise: 'USD',
        taux_change: null,
        date: '2026-07-05',
        fournisseur_id: 'four-001',
      },
      {
        id: 'cout-202',
        dossier_id: 'dos-003',
        type: 'inspection',
        montant: 400,
        devise: 'USD',
        taux_change: null,
        date: '',
        fournisseur_id: null,
      },
    ],
    documents: [
      {
        id: 'doc-401',
        dossier_id: 'dos-003',
        type: 'contrat',
        nom: 'Contrat_signe.pdf',
        taille: '1.4 Mo',
        url: '#',
        upload_par: 'S. Mansouri',
        date: '2026-07-01',
        version: 1,
        statut: 'valide',
        notes: '',
      },
      {
        id: 'doc-402',
        dossier_id: 'dos-003',
        type: 'pi_fournisseur',
        nom: 'Proforma_SinoAuto.pdf',
        taille: '0.7 Mo',
        url: '#',
        upload_par: 'W. Liu',
        date: '2026-06-28',
        version: 1,
        statut: 'recu',
        notes: '',
      },
      {
        id: 'doc-403',
        dossier_id: 'dos-003',
        type: 'rapport_inspection',
        nom: 'Inspection_GLE_Q7.pdf',
        taille: '2.4 Mo',
        url: '#',
        upload_par: 'W. Liu',
        date: '',
        version: 1,
        statut: 'en_attente',
        notes: 'Prévue après le solde fournisseur',
      },
      {
        id: 'doc-404',
        dossier_id: 'dos-003',
        type: 'documents_vehicule',
        nom: 'COC_GLE.pdf',
        taille: '0.9 Mo',
        url: '#',
        upload_par: 'W. Liu',
        date: '',
        version: 1,
        statut: 'manquant',
        notes: 'À récupérer auprès du fournisseur',
      },
    ],
    taches: [
      {
        id: 'tac-201',
        dossier_id: 'dos-003',
        titre: 'Planifier l\u2019inspection des deux véhicules',
        assigne_a: 'W. Liu',
        departement: 'Ops Chine',
        date_echeance: '2026-08-18',
        priorite: 'haute',
        statut: 'a_faire',
        description: 'Bloquer une date d\u2019inspection avant le solde fournisseur.',
        commentaires: '',
      },
      {
        id: 'tac-202',
        dossier_id: 'dos-003',
        titre: 'Récupérer les COC',
        assigne_a: 'W. Liu',
        departement: 'Ops Chine',
        date_echeance: '2026-08-22',
        priorite: 'normale',
        statut: 'a_faire',
        description: 'Demander les certificats de conformité des 2 véhicules.',
        commentaires: '',
      },
    ],
    timeline: [
      {
        id: 'tim-401',
        dossier_id: 'dos-003',
        date: '2026-06-25T09:00:00',
        utilisateur: 'A. Djelloul',
        action: 'Dossier créé',
        type: 'systeme',
        details: 'Dossier ouvert pour N. Zerhouni (2 véhicules)',
      },
      {
        id: 'tim-402',
        dossier_id: 'dos-003',
        date: '2026-07-01T10:00:00',
        utilisateur: 'S. Mansouri',
        action: 'Contrat signé',
        type: 'document',
        details: 'Acompte de 3 000 000 DA reçu',
      },
      {
        id: 'tim-403',
        dossier_id: 'dos-003',
        date: '2026-07-05T14:00:00',
        utilisateur: 'F. Boukhris',
        action: 'Acompte fournisseur payé',
        type: 'paiement',
        details: '30 000 $ versés à Sino Auto Ltd',
      },
    ],
    notes: [
      {
        id: 'not-201',
        dossier_id: 'dos-003',
        auteur: 'W. Liu',
        date: '2026-07-10T11:00:00',
        contenu:
          'Sino Auto propose de grouper les 2 véhicules dans un seul conteneur pour économiser le fret.',
      },
    ],
  },
  {
    id: 'dos-004',
    reference: 'CA-2026-0051',
    type: 'ddp',
    client_id: 'cli-004',
    client_nom: 'Y. Messaoudi',
    fournisseur_nom: 'Pacific Vehicle Trading',
    statut: 'douane',
    origine: 'client',
    date_creation: '2026-07-20',
    date_mise_a_jour: '2026-08-12',
    responsable_chine_id: 'usr-003',
    responsable_algerie_id: 'usr-002',
    offre_id: 'off-004',
    supplier_id: 'four-003',
    contrat_statut: 'signe',
    contrat_date: '2026-07-25',
    client: clients[3],
    vehicles: [vehicules[3]],
    purchase: {
      id: 'PUR-2026-0026',
      dossier_id: 'dos-004',
      vehicle_id: 'veh-004',
      supplier_id: 'four-003',
      montant: 55000,
      devise: 'USD',
      acompte_fournisseur: 25000,
      solde_fournisseur: 30000,
      statut_paiement: 'partiel',
      date_echeance: '2026-08-28',
      conditions_negociees: 'Acompte 25 000 $, solde à la sortie du port.',
      responsable_chine_id: 'usr-003',
      documents: ['Proforma_Pacific.pdf', 'Preuve_acompte_fournisseur.pdf'],
    },
    paiements_client: [
      {
        id: 'pay-301',
        dossier_id: 'dos-004',
        type: 'acompte',
        montant: 2500000,
        devise: 'DZD',
        taux_change: 0.0077,
        date: '2026-07-25',
        methode: 'Virement bancaire',
      },
      {
        id: 'pay-302',
        dossier_id: 'dos-004',
        type: 'final',
        montant: 40000,
        devise: 'USD',
        taux_change: null,
        date: '',
        methode: 'Espèces agence',
      },
      {
        id: 'pay-303',
        dossier_id: 'dos-004',
        type: 'douane',
        montant: 3264000,
        devise: 'DZD',
        taux_change: 0.0077,
        date: '',
        methode: 'Virement bancaire',
      },
    ],
    couts: [
      {
        id: 'cout-301',
        dossier_id: 'dos-004',
        type: 'achat_vehicule',
        montant: 55000,
        devise: 'USD',
        taux_change: null,
        date: '2026-07-28',
        fournisseur_id: 'four-003',
      },
      {
        id: 'cout-302',
        dossier_id: 'dos-004',
        type: 'shipping',
        montant: 2000,
        devise: 'USD',
        taux_change: null,
        date: '2026-08-02',
        fournisseur_id: null,
      },
      {
        id: 'cout-303',
        dossier_id: 'dos-004',
        type: 'douane',
        montant: 3264000,
        devise: 'DZD',
        taux_change: 0.0077,
        date: '2026-08-11',
        fournisseur_id: null,
      },
    ],
    expedition: {
      numero_conteneur: 'HLXU-7654-3',
      navire: 'HAPAG-LLOYD BERLIN EXPRESS',
      numero_bl: 'HLXUBJ901234',
      port_depart: 'Tianjin, CN',
      port_arrivee: 'Alger, DZ',
      etd: '2026-07-15',
      eta: '2026-08-10',
      statut: 'arrivee',
    },
    douane: {
      numero_declaration: 'DD-2026-5892',
      date_declaration: '2026-08-11',
      bureau_douane: 'Bureau Alger Port',
      valeur_declaree_dzd: 10200000,
      droits_douane_dzd: 2040000,
      tva_dzd: 1224000,
      total_frais_dzd: 3264000,
      statut: 'en_cours',
      date_dedouanement: null,
    },
    documents: [
      {
        id: 'doc-501',
        dossier_id: 'dos-004',
        type: 'contrat',
        nom: 'Contrat_signe.pdf',
        taille: '1.3 Mo',
        url: '#',
        upload_par: 'S. Mansouri',
        date: '2026-07-25',
        version: 1,
        statut: 'valide',
        notes: '',
      },
      {
        id: 'doc-502',
        dossier_id: 'dos-004',
        type: 'documents_douane',
        nom: 'Déclaration_douane.pdf',
        taille: '1.1 Mo',
        url: '#',
        upload_par: 'K. Rahmani',
        date: '2026-08-11',
        version: 1,
        statut: 'en_attente',
        notes: 'En cours de validation au bureau Alger Port',
      },
      {
        id: 'doc-503',
        dossier_id: 'dos-004',
        type: 'bl_final',
        nom: 'BL_final_HLXU7654.pdf',
        taille: '0.5 Mo',
        url: '#',
        upload_par: 'K. Rahmani',
        date: '2026-08-10',
        version: 1,
        statut: 'recu',
        notes: '',
      },
    ],
    taches: [
      {
        id: 'tac-301',
        dossier_id: 'dos-004',
        titre: 'Suivre la validation de la déclaration douane',
        assigne_a: 'K. Rahmani',
        departement: 'Shipping',
        date_echeance: '2026-08-15',
        priorite: 'urgente',
        statut: 'en_cours',
        description: 'Relancer le bureau de douane pour la mainlevée.',
        commentaires: '',
      },
    ],
    timeline: [
      {
        id: 'tim-501',
        dossier_id: 'dos-004',
        date: '2026-07-20T09:00:00',
        utilisateur: 'A. Djelloul',
        action: 'Dossier créé',
        type: 'systeme',
        details: 'Dossier DDP ouvert pour Y. Messaoudi (Land Cruiser)',
      },
      {
        id: 'tim-502',
        dossier_id: 'dos-004',
        date: '2026-07-25T10:00:00',
        utilisateur: 'S. Mansouri',
        action: 'Contrat signé',
        type: 'document',
        details: 'Acompte de 2 500 000 DA reçu',
      },
      {
        id: 'tim-503',
        dossier_id: 'dos-004',
        date: '2026-08-11T09:30:00',
        utilisateur: 'K. Rahmani',
        action: 'Statut → Douane',
        type: 'statut',
        details: 'Véhicule arrivé à Alger, déclaration déposée',
      },
    ],
    notes: [],
  },
  {
    id: 'dos-005',
    reference: 'CA-2026-0012',
    type: 'cif',
    client_id: 'cli-005',
    client_nom: 'A. Bouzid',
    fournisseur_nom: 'Yangtze Auto Group',
    statut: 'documents_remis',
    origine: 'client',
    date_creation: '2026-03-01',
    date_mise_a_jour: '2026-06-30',
    responsable_chine_id: 'usr-003',
    responsable_algerie_id: 'usr-002',
    offre_id: 'off-006',
    supplier_id: 'four-005',
    contrat_statut: 'signe',
    contrat_date: '2026-03-08',
    client: clients[4],
    vehicles: [vehicules[5]],
    purchase: {
      id: 'PUR-2026-0008',
      dossier_id: 'dos-005',
      vehicle_id: 'veh-006',
      supplier_id: 'four-005',
      montant: 78000,
      devise: 'USD',
      acompte_fournisseur: 78000,
      solde_fournisseur: 0,
      statut_paiement: 'paye',
      date_echeance: null,
      conditions_negociees: 'Paiement intégral à la commande.',
      responsable_chine_id: 'usr-003',
      documents: ['Proforma_Yangtze.pdf'],
    },
    paiements_client: [
      {
        id: 'pay-401',
        dossier_id: 'dos-005',
        type: 'acompte',
        montant: 5000000,
        devise: 'DZD',
        taux_change: 0.0077,
        date: '2026-03-08',
        methode: 'Virement bancaire',
      },
      {
        id: 'pay-402',
        dossier_id: 'dos-005',
        type: 'final',
        montant: 45000,
        devise: 'USD',
        taux_change: null,
        date: '2026-06-15',
        methode: 'Virement bancaire',
      },
    ],
    couts: [
      {
        id: 'cout-401',
        dossier_id: 'dos-005',
        type: 'achat_vehicule',
        montant: 78000,
        devise: 'USD',
        taux_change: null,
        date: '2026-03-10',
        fournisseur_id: 'four-005',
      },
      {
        id: 'cout-402',
        dossier_id: 'dos-005',
        type: 'shipping',
        montant: 2200,
        devise: 'USD',
        taux_change: null,
        date: '2026-04-20',
        fournisseur_id: null,
      },
      {
        id: 'cout-403',
        dossier_id: 'dos-005',
        type: 'port',
        montant: 350,
        devise: 'USD',
        taux_change: null,
        date: '2026-05-30',
        fournisseur_id: null,
      },
    ],
    douane: {
      numero_declaration: 'DD-2026-2103',
      date_declaration: '2026-06-01',
      bureau_douane: 'Bureau Alger Port',
      valeur_declaree_dzd: 13900000,
      droits_douane_dzd: 2780000,
      tva_dzd: 1668000,
      total_frais_dzd: 4448000,
      statut: 'validee',
      date_dedouanement: '2026-06-05',
    },
    documents: documentsDossier005,
    taches: [
      {
        id: 'tac-401',
        dossier_id: 'dos-005',
        titre: 'Préparer le dossier de clôture',
        assigne_a: 'A. Djelloul',
        departement: 'Admin',
        date_echeance: '2026-07-05',
        priorite: 'basse',
        statut: 'a_faire',
        description: 'Rassembler tous les documents avant archivage.',
        commentaires: '',
      },
    ],
    timeline: timelineDossier005,
    notes: [],
  },
  {
    id: 'dos-006',
    reference: 'CA-2026-0058',
    type: 'cif',
    client_id: 'cli-006',
    client_nom: 'M. Khelifi',
    fournisseur_nom: 'Eastern Horizon Motors',
    statut: 'chargement',
    origine: 'stock',
    date_creation: '2026-08-01',
    date_mise_a_jour: '2026-08-14',
    responsable_chine_id: 'usr-003',
    responsable_algerie_id: 'usr-002',
    offre_id: 'off-007',
    supplier_id: 'four-006',
    contrat_statut: 'brouillon',
    contrat_date: null,
    client: clients[5],
    vehicles: [vehicules[8]],
    purchase: {
      id: 'PUR-2026-0028',
      dossier_id: 'dos-006',
      vehicle_id: 'veh-009',
      supplier_id: 'four-006',
      montant: 30000,
      devise: 'USD',
      acompte_fournisseur: 30000,
      solde_fournisseur: 0,
      statut_paiement: 'paye',
      date_echeance: null,
      conditions_negociees: 'Achat stock Corapide, véhicule en stock à Guangzhou.',
      responsable_chine_id: 'usr-003',
      documents: ['Proforma_Eastern.pdf'],
    },
    paiements_client: [
      {
        id: 'pay-501',
        dossier_id: 'dos-006',
        type: 'acompte',
        montant: 3000000,
        devise: 'DZD',
        taux_change: 0.0077,
        date: '2026-08-05',
        methode: 'Virement bancaire',
      },
    ],
    couts: [
      {
        id: 'cout-501',
        dossier_id: 'dos-006',
        type: 'achat_vehicule',
        montant: 30000,
        devise: 'USD',
        taux_change: null,
        date: '2026-08-03',
        fournisseur_id: 'four-006',
      },
      {
        id: 'cout-502',
        dossier_id: 'dos-006',
        type: 'inspection',
        montant: 150,
        devise: 'USD',
        taux_change: null,
        date: '2026-08-06',
        fournisseur_id: null,
      },
    ],
    expedition: {
      numero_conteneur: 'CMAU-4521-7',
      navire: 'CMA CGM MARCO POLO',
      numero_bl: 'CMAUGZ789012',
      port_depart: 'Guangzhou, CN',
      port_arrivee: 'Alger, DZ',
      etd: '2026-08-20',
      eta: '2026-09-15',
      statut: 'planifiee',
    },
    documents: [
      {
        id: 'doc-601',
        dossier_id: 'dos-006',
        type: 'contrat',
        nom: 'Contrat_brouillon.pdf',
        taille: '0.9 Mo',
        url: '#',
        upload_par: 'S. Mansouri',
        date: '2026-08-05',
        version: 1,
        statut: 'en_attente',
        notes: 'En attente de signature du client',
      },
      {
        id: 'doc-602',
        dossier_id: 'dos-006',
        type: 'rapport_inspection',
        nom: 'Inspection_Tucson.pdf',
        taille: '1.6 Mo',
        url: '#',
        upload_par: 'W. Liu',
        date: '2026-08-06',
        version: 1,
        statut: 'recu',
        notes: '',
      },
      {
        id: 'doc-603',
        dossier_id: 'dos-006',
        type: 'bl_draft',
        nom: 'BL_draft_CMAU4521.pdf',
        taille: '0.4 Mo',
        url: '#',
        upload_par: 'K. Rahmani',
        date: '',
        version: 1,
        statut: 'manquant',
        notes: '',
      },
    ],
    taches: [
      {
        id: 'tac-501',
        dossier_id: 'dos-006',
        titre: 'Obtenir la signature du client sur le contrat',
        assigne_a: 'S. Mansouri',
        departement: 'Sales Algérie',
        date_echeance: '2026-08-18',
        priorite: 'haute',
        statut: 'en_cours',
        description: 'Relancer M. Khelifi pour signer le contrat.',
        commentaires: '',
      },
      {
        id: 'tac-502',
        dossier_id: 'dos-006',
        titre: 'Confirmer le booking CMA CGM',
        assigne_a: 'K. Rahmani',
        departement: 'Shipping',
        date_echeance: '2026-08-16',
        priorite: 'haute',
        statut: 'a_faire',
        description: 'Confirmer la réservation du conteneur avant l\u2019ETD.',
        commentaires: '',
      },
    ],
    timeline: [
      {
        id: 'tim-601',
        dossier_id: 'dos-006',
        date: '2026-08-01T09:00:00',
        utilisateur: 'A. Djelloul',
        action: 'Dossier créé',
        type: 'systeme',
        details: 'Dossier stock — Hyundai Tucson vendu depuis le stock Corapide',
      },
      {
        id: 'tim-602',
        dossier_id: 'dos-006',
        date: '2026-08-03T10:00:00',
        utilisateur: 'F. Boukhris',
        action: 'Achat payé',
        type: 'paiement',
        details: '30 000 $ réglés à Eastern Horizon Motors',
      },
    ],
    notes: [],
  },
  {
    id: 'dos-007',
    reference: 'CA-2026-0060',
    type: 'cif',
    client_id: 'cli-001',
    client_nom: 'B. Amrani',
    fournisseur_nom: null,
    statut: 'offre_selectionnee',
    origine: 'client',
    date_creation: '2026-08-14',
    date_mise_a_jour: '2026-08-15',
    responsable_chine_id: null,
    responsable_algerie_id: 'usr-002',
    offre_id: null,
    supplier_id: null,
    contrat_statut: 'brouillon',
    contrat_date: null,
    client: clients[0],
    vehicles: [],
    paiements_client: [],
    couts: [],
    documents: [
      {
        id: 'doc-701',
        dossier_id: 'dos-007',
        type: 'id_client',
        nom: 'Passeport_client.pdf',
        taille: '2.0 Mo',
        url: '#',
        upload_par: 'S. Mansouri',
        date: '2026-08-14',
        version: 1,
        statut: 'recu',
        notes: '',
      },
      {
        id: 'doc-702',
        dossier_id: 'dos-007',
        type: 'contrat',
        nom: 'Contrat_brouillon.pdf',
        taille: '0.8 Mo',
        url: '#',
        upload_par: 'S. Mansouri',
        date: '2026-08-15',
        version: 1,
        statut: 'manquant',
        notes: 'À faire signer par le client',
      },
    ],
    taches: [
      {
        id: 'tac-701',
        dossier_id: 'dos-007',
        titre: 'Envoyer le contrat au client',
        assigne_a: 'S. Mansouri',
        departement: 'Sales Algérie',
        date_echeance: '2026-08-18',
        priorite: 'haute',
        statut: 'a_faire',
        description: 'Envoyer le contrat brouillon et attendre la signature.',
        commentaires: '',
      },
    ],
    timeline: [
      {
        id: 'tim-701',
        dossier_id: 'dos-007',
        date: '2026-08-14T09:00:00',
        utilisateur: 'S. Mansouri',
        action: 'Dossier créé',
        type: 'systeme',
        details: 'Dossier ouvert pour un second véhicule de B. Amrani',
      },
    ],
    notes: [
      {
        id: 'not-701',
        dossier_id: 'dos-007',
        auteur: 'S. Mansouri',
        date: '2026-08-15T10:00:00',
        contenu:
          'Le client cherche un BMW X6 2022. Proposition en cours — offre à confirmer.',
      },
    ],
  },
  {
    id: 'dos-008',
    reference: 'CA-2026-0066',
    type: 'ddp',
    client_id: 'cli-002',
    client_nom: 'K. Benali',
    fournisseur_nom: 'Externe — client',
    statut: 'transport_local',
    origine: 'client',
    date_creation: '2026-07-01',
    date_mise_a_jour: '2026-08-16',
    responsable_chine_id: null,
    responsable_algerie_id: 'usr-002',
    offre_id: null,
    supplier_id: null,
    contrat_statut: 'signe',
    contrat_date: '2026-07-05',
    client: clients[1],
    vehicles: [vehicules[6]],
    paiements_client: [
      {
        id: 'pay-601',
        dossier_id: 'dos-008',
        type: 'acompte',
        montant: 800000,
        devise: 'DZD',
        taux_change: 0.0077,
        date: '2026-07-05',
        methode: 'Virement bancaire',
      },
      {
        id: 'pay-602',
        dossier_id: 'dos-008',
        type: 'douane',
        montant: 1500000,
        devise: 'DZD',
        taux_change: 0.0077,
        date: '2026-08-10',
        methode: 'Virement bancaire',
      },
    ],
    couts: [
      {
        id: 'cout-601',
        dossier_id: 'dos-008',
        type: 'douane',
        montant: 1500000,
        devise: 'DZD',
        taux_change: 0.0077,
        date: '2026-08-10',
        fournisseur_id: null,
      },
      {
        id: 'cout-602',
        dossier_id: 'dos-008',
        type: 'transport_local',
        montant: 400,
        devise: 'USD',
        taux_change: null,
        date: '',
        fournisseur_id: null,
      },
    ],
    douane: {
      numero_declaration: 'DD-2026-6130',
      date_declaration: '2026-08-09',
      bureau_douane: 'Bureau Alger Port',
      valeur_declaree_dzd: 4500000,
      droits_douane_dzd: 900000,
      tva_dzd: 540000,
      total_frais_dzd: 1500000,
      statut: 'validee',
      date_dedouanement: '2026-08-12',
    },
    documents: [
      {
        id: 'doc-801',
        dossier_id: 'dos-008',
        type: 'contrat',
        nom: 'Contrat_signe.pdf',
        taille: '1.1 Mo',
        url: '#',
        upload_par: 'S. Mansouri',
        date: '2026-07-05',
        version: 1,
        statut: 'valide',
        notes: '',
      },
      {
        id: 'doc-802',
        dossier_id: 'dos-008',
        type: 'documents_douane',
        nom: 'Déclaration_douane.pdf',
        taille: '1.0 Mo',
        url: '#',
        upload_par: 'K. Rahmani',
        date: '2026-08-09',
        version: 1,
        statut: 'valide',
        notes: 'Mainlevée obtenue le 12/08',
      },
      {
        id: 'doc-803',
        dossier_id: 'dos-008',
        type: 'document_livraison',
        nom: 'PV_livraison.pdf',
        taille: '0.6 Mo',
        url: '#',
        upload_par: 'S. Mansouri',
        date: '',
        version: 1,
        statut: 'manquant',
        notes: 'À établir après livraison',
      },
    ],
    taches: [
      {
        id: 'tac-801',
        dossier_id: 'dos-008',
        titre: 'Organiser le transport local vers Oran',
        assigne_a: 'S. Mansouri',
        departement: 'Sales Algérie',
        date_echeance: '2026-08-18',
        priorite: 'haute',
        statut: 'a_faire',
        description: 'Réserver un transporteur pour livrer le véhicule à Oran.',
        commentaires: '',
      },
    ],
    timeline: [
      {
        id: 'tim-801',
        dossier_id: 'dos-008',
        date: '2026-07-01T09:00:00',
        utilisateur: 'A. Djelloul',
        action: 'Dossier créé',
        type: 'systeme',
        details: 'Véhicule externe — service DDP pour K. Benali',
      },
      {
        id: 'tim-802',
        dossier_id: 'dos-008',
        date: '2026-08-12T10:00:00',
        utilisateur: 'K. Rahmani',
        action: 'Mainlevée obtenue',
        type: 'statut',
        details: 'Véhicule dédouané à Alger',
      },
    ],
    notes: [],
  },
  {
    id: 'dos-009',
    reference: 'CA-2026-0069',
    type: 'shipping_only',
    client_id: 'cli-003',
    client_nom: 'N. Zerhouni',
    fournisseur_nom: 'Externe — client',
    statut: 'service_termine',
    origine: 'client',
    date_creation: '2026-06-15',
    date_mise_a_jour: '2026-07-30',
    responsable_chine_id: null,
    responsable_algerie_id: 'usr-002',
    offre_id: null,
    supplier_id: null,
    contrat_statut: 'signe',
    contrat_date: '2026-06-18',
    client: clients[2],
    vehicles: [vehicules[7]],
    paiements_client: [
      {
        id: 'pay-701',
        dossier_id: 'dos-009',
        type: 'acompte',
        montant: 1200000,
        devise: 'DZD',
        taux_change: 0.0077,
        date: '2026-06-18',
        methode: 'Virement bancaire',
      },
      {
        id: 'pay-702',
        dossier_id: 'dos-009',
        type: 'final',
        montant: 2800000,
        devise: 'DZD',
        taux_change: 0.0077,
        date: '2026-07-20',
        methode: 'Virement bancaire',
      },
    ],
    couts: [
      {
        id: 'cout-701',
        dossier_id: 'dos-009',
        type: 'pickup',
        montant: 150,
        devise: 'USD',
        taux_change: null,
        date: '2026-06-20',
        fournisseur_id: null,
      },
      {
        id: 'cout-702',
        dossier_id: 'dos-009',
        type: 'shipping',
        montant: 1800,
        devise: 'USD',
        taux_change: null,
        date: '2026-06-22',
        fournisseur_id: null,
      },
      {
        id: 'cout-703',
        dossier_id: 'dos-009',
        type: 'port',
        montant: 250,
        devise: 'USD',
        taux_change: null,
        date: '2026-07-06',
        fournisseur_id: null,
      },
    ],
    documents: documentsDossier009,
    taches: [
      {
        id: 'tac-901',
        dossier_id: 'dos-009',
        titre: 'Clôturer le dossier',
        assigne_a: 'A. Djelloul',
        departement: 'Admin',
        date_echeance: '2026-08-05',
        priorite: 'basse',
        statut: 'en_cours',
        description: 'Confirmer la satisfaction client et clôturer.',
        commentaires: '',
      },
    ],
    timeline: timelineDossier009,
    notes: [],
  },
  {
    id: 'dos-010',
    reference: 'CA-2026-0072',
    type: 'shipping_only',
    client_id: 'cli-004',
    client_nom: 'Y. Messaoudi',
    fournisseur_nom: 'Externe — client',
    statut: 'paiement',
    origine: 'client',
    date_creation: '2026-08-10',
    date_mise_a_jour: '2026-08-16',
    responsable_chine_id: null,
    responsable_algerie_id: 'usr-002',
    offre_id: null,
    supplier_id: null,
    contrat_statut: 'brouillon',
    contrat_date: null,
    client: clients[3],
    vehicles: [vehicules[9]],
    paiements_client: [
      {
        id: 'pay-801',
        dossier_id: 'dos-010',
        type: 'acompte',
        montant: 500000,
        devise: 'DZD',
        taux_change: 0.0077,
        date: '2026-08-12',
        methode: 'Virement bancaire',
      },
    ],
    couts: [],
    documents: [
      {
        id: 'doc-901',
        dossier_id: 'dos-010',
        type: 'id_client',
        nom: 'Passeport_client.pdf',
        taille: '1.9 Mo',
        url: '#',
        upload_par: 'S. Mansouri',
        date: '2026-08-10',
        version: 1,
        statut: 'recu',
        notes: '',
      },
      {
        id: 'doc-902',
        dossier_id: 'dos-010',
        type: 'contrat',
        nom: 'Contrat_brouillon.pdf',
        taille: '0.8 Mo',
        url: '#',
        upload_par: 'S. Mansouri',
        date: '2026-08-12',
        version: 1,
        statut: 'manquant',
        notes: 'En attente de signature',
      },
    ],
    taches: [
      {
        id: 'tac-901',
        dossier_id: 'dos-010',
        titre: 'Confirmer le paiement shipping',
        assigne_a: 'F. Boukhris',
        departement: 'Finance',
        date_echeance: '2026-08-20',
        priorite: 'haute',
        statut: 'en_cours',
        description: 'Relancer le client pour le solde du devis shipping.',
        commentaires: '',
      },
    ],
    timeline: [
      {
        id: 'tim-901',
        dossier_id: 'dos-010',
        date: '2026-08-10T09:00:00',
        utilisateur: 'A. Djelloul',
        action: 'Dossier créé',
        type: 'systeme',
        details: 'Expédition seule — Mercedes GLC 300',
      },
      {
        id: 'tim-902',
        dossier_id: 'dos-010',
        date: '2026-08-12T10:00:00',
        utilisateur: 'S. Mansouri',
        action: 'Acompte reçu',
        type: 'paiement',
        details: '500 000 DA reçus, devis en attente de confirmation',
      },
    ],
    notes: [],
  },
];

// ─── Helper: find entities ───────────────────────────────────────────

export function getDossierById(id: string): Dossier | undefined {
  return dossiers.find((d) => d.id === id);
}

export function getClientById(id: string): Client | undefined {
  return clients.find((c) => c.id === id);
}

export function getVehiculeById(id: string): Vehicule | undefined {
  return vehicules.find((v) => v.id === id);
}

export function getFournisseurById(id: string): Fournisseur | undefined {
  return fournisseurs.find((f) => f.id === id);
}

export function getOffreById(id: string): Offre | undefined {
  return offres.find((o) => o.id === id);
}

export function getUtilisateurById(id: string): Utilisateur | undefined {
  return utilisateurs.find((u) => u.id === id);
}
