import type {
  Client,
  Fournisseur,
  Vehicule,
  Dossier,
  Facture,
  Utilisateur,
  Expedition,
  DocumentDossier,
  HistoriqueEntry,
  ExpeditionInfo,
  DouaneInfo,
} from '@/types';

// ─── Clients ─────────────────────────────────────────────────────────

export const clients: Client[] = [
  {
    id: 'cli-001',
    nom: 'Amrani',
    prenom: 'Brahim',
    telephone: '+213 555 123 456',
    email: 'b.amrani@email.dz',
    numero_passeport: 'C-2849201',
    adresse: 'Alger, Hydra',
    date_inscription: '2026-01-15',
    nombre_dossiers: 2,
  },
  {
    id: 'cli-002',
    nom: 'Benali',
    prenom: 'Karim',
    telephone: '+213 555 234 567',
    email: 'k.benali@email.dz',
    numero_passeport: 'C-3921847',
    adresse: 'Oran, Bir El Djir',
    date_inscription: '2026-02-20',
    nombre_dossiers: 1,
  },
  {
    id: 'cli-003',
    nom: 'Zerhouni',
    prenom: 'Nadia',
    telephone: '+213 555 345 678',
    email: 'n.zerhouni@email.dz',
    numero_passeport: 'C-1029384',
    adresse: 'Constantine, Centre',
    date_inscription: '2026-03-10',
    nombre_dossiers: 1,
  },
  {
    id: 'cli-004',
    nom: 'Messaoudi',
    prenom: 'Youcef',
    telephone: '+213 555 456 789',
    email: 'y.messaoudi@email.dz',
    numero_passeport: 'C-5738291',
    adresse: 'Annaba, Sidi Amar',
    date_inscription: '2026-04-05',
    nombre_dossiers: 1,
  },
  {
    id: 'cli-005',
    nom: 'Bouzid',
    prenom: 'Amina',
    telephone: '+213 555 567 890',
    email: 'a.bouzid@email.dz',
    numero_passeport: 'C-8472019',
    adresse: 'Tlemcen, Centre',
    date_inscription: '2026-05-12',
    nombre_dossiers: 1,
  },
  {
    id: 'cli-006',
    nom: 'Khelifi',
    prenom: 'Mohamed',
    telephone: '+213 555 678 901',
    email: 'm.khelifi@email.dz',
    numero_passeport: 'C-6192837',
    adresse: 'Sétif, Centre',
    date_inscription: '2026-06-01',
    nombre_dossiers: 1,
  },
];

// ─── Fournisseurs ────────────────────────────────────────────────────

export const fournisseurs: Fournisseur[] = [
  {
    id: 'four-001',
    nom: 'Sino Auto Ltd',
    pays: 'Chine',
    ville: 'Shanghai',
    contact: 'Li Wei',
    email: 'liwei@sinoauto.cn',
    telephone: '+86 21 5555 1234',
    nombre_vehicules: 12,
  },
  {
    id: 'four-002',
    nom: 'Dragon Motors Co.',
    pays: 'Chine',
    ville: 'Guangzhou',
    contact: 'Zhang Min',
    email: 'zhang.min@dragonmotors.cn',
    telephone: '+86 20 6666 5678',
    nombre_vehicules: 8,
  },
  {
    id: 'four-003',
    nom: 'Pacific Vehicle Trading',
    pays: 'Chine',
    ville: 'Shenzhen',
    contact: 'Chen Hao',
    email: 'chen@pacificvt.cn',
    telephone: '+86 755 8888 9012',
    nombre_vehicules: 15,
  },
  {
    id: 'four-004',
    nom: 'Golden Star Auto Export',
    pays: 'Chine',
    ville: 'Beijing',
    contact: 'Wang Jun',
    email: 'wangjun@goldenstar.cn',
    telephone: '+86 10 7777 3456',
    nombre_vehicules: 6,
  },
  {
    id: 'four-005',
    nom: 'Yangtze Auto Group',
    pays: 'Chine',
    ville: 'Chongqing',
    contact: 'Liu Fang',
    email: 'liu.fang@yangtzeauto.cn',
    telephone: '+86 23 4444 7890',
    nombre_vehicules: 10,
  },
  {
    id: 'four-006',
    nom: 'Eastern Horizon Motors',
    pays: 'Chine',
    ville: 'Tianjin',
    contact: 'Xu Peng',
    email: 'xupeng@ehorizon.cn',
    telephone: '+86 22 3333 2345',
    nombre_vehicules: 4,
  },
];

// ─── Véhicules ───────────────────────────────────────────────────────

export const vehicules: Vehicule[] = [
  {
    id: 'veh-001',
    vin: 'WBAFG01010L191234',
    marque: 'BMW',
    modele: 'X5',
    annee: 2023,
    couleur: 'Noir',
    prix_achat_cny: 350000,
    prix_achat_dzd: 6500000,
    fournisseur_id: 'four-001',
    fournisseur_nom: 'Sino Auto Ltd',
    statut: 'en_mer',
    photos: [],
    date_ajout: '2026-06-15',
  },
  {
    id: 'veh-002',
    vin: 'LSVAU2A89NE012345',
    marque: 'Audi',
    modele: 'Q7',
    annee: 2024,
    couleur: 'Blanc',
    prix_achat_cny: 420000,
    prix_achat_dzd: 7800000,
    fournisseur_id: 'four-002',
    fournisseur_nom: 'Dragon Motors Co.',
    statut: 'disponible',
    photos: [],
    date_ajout: '2026-05-20',
  },
  {
    id: 'veh-003',
    vin: 'WDC2539632A891011',
    marque: 'Mercedes-Benz',
    modele: 'GLE 350',
    annee: 2024,
    couleur: 'Gris',
    prix_achat_cny: 480000,
    prix_achat_dzd: 8900000,
    fournisseur_id: 'four-001',
    fournisseur_nom: 'Sino Auto Ltd',
    statut: 'reserve',
    photos: [],
    date_ajout: '2026-04-10',
  },
  {
    id: 'veh-004',
    vin: 'JTDKN3DU5A5678901',
    marque: 'Toyota',
    modele: 'Land Cruiser',
    annee: 2023,
    couleur: 'Blanc',
    prix_achat_cny: 550000,
    prix_achat_dzd: 10200000,
    fournisseur_id: 'four-003',
    fournisseur_nom: 'Pacific Vehicle Trading',
    statut: 'en_douane',
    photos: [],
    date_ajout: '2026-03-25',
  },
  {
    id: 'veh-005',
    vin: 'SALGS2RE5LA234567',
    marque: 'Range Rover',
    modele: 'Sport',
    annee: 2024,
    couleur: 'Vert',
    prix_achat_cny: 620000,
    prix_achat_dzd: 11500000,
    fournisseur_id: 'four-004',
    fournisseur_nom: 'Golden Star Auto Export',
    statut: 'livre',
    photos: [],
    date_ajout: '2026-02-18',
  },
  {
    id: 'veh-006',
    vin: 'WP0AA2A98KS345678',
    marque: 'Porsche',
    modele: 'Cayenne',
    annee: 2024,
    couleur: 'Rouge',
    prix_achat_cny: 750000,
    prix_achat_dzd: 13900000,
    fournisseur_id: 'four-005',
    fournisseur_nom: 'Yangtze Auto Group',
    statut: 'vendu',
    photos: [],
    date_ajout: '2026-01-10',
  },
];

// ─── Factures ────────────────────────────────────────────────────────

export const factures: Facture[] = [
  {
    id: 'fac-001',
    reference: 'FAC-2026-081',
    dossier_id: 'dos-001',
    dossier_reference: 'CA-2026-0032',
    libelle: 'Acompte',
    montant_dzd: 1600000,
    date: '2026-08-01',
    statut: 'payee',
  },
  {
    id: 'fac-002',
    reference: 'FAC-2026-102',
    dossier_id: 'dos-001',
    dossier_reference: 'CA-2026-0032',
    libelle: 'Solde partiel',
    montant_dzd: 800000,
    date: '2026-08-10',
    statut: 'en_attente',
  },
  {
    id: 'fac-003',
    reference: 'FAC-2026-115',
    dossier_id: 'dos-001',
    dossier_reference: 'CA-2026-0032',
    libelle: 'Frais douane',
    montant_dzd: 400000,
    date: '2026-08-15',
    statut: 'en_retard',
  },
  {
    id: 'fac-004',
    reference: 'FAC-2026-043',
    dossier_id: 'dos-002',
    dossier_reference: 'CA-2026-0018',
    libelle: 'Acompte',
    montant_dzd: 2000000,
    date: '2026-05-15',
    statut: 'payee',
  },
  {
    id: 'fac-005',
    reference: 'FAC-2026-044',
    dossier_id: 'dos-002',
    dossier_reference: 'CA-2026-0018',
    libelle: 'Solde final',
    montant_dzd: 5800000,
    date: '2026-06-20',
    statut: 'payee',
  },
  {
    id: 'fac-006',
    reference: 'FAC-2026-120',
    dossier_id: 'dos-003',
    dossier_reference: 'CA-2026-0045',
    libelle: 'Acompte',
    montant_dzd: 3000000,
    date: '2026-07-01',
    statut: 'payee',
  },
  {
    id: 'fac-007',
    reference: 'FAC-2026-150',
    dossier_id: 'dos-004',
    dossier_reference: 'CA-2026-0051',
    libelle: 'Acompte',
    montant_dzd: 2500000,
    date: '2026-07-20',
    statut: 'en_attente',
  },
];

// ─── Documents ───────────────────────────────────────────────────────

export const documentsDossier001: DocumentDossier[] = [
  {
    id: 'doc-001',
    nom: 'Contrat_signé.pdf',
    type: 'Contrat',
    date: '2026-08-01',
    taille: '1.2 Mo',
    url: '#',
  },
  {
    id: 'doc-002',
    nom: 'Facture_acompte.pdf',
    type: 'Facture',
    date: '2026-08-01',
    taille: '0.8 Mo',
    url: '#',
  },
  {
    id: 'doc-003',
    nom: 'Passeport_client.pdf',
    type: "Pièce d'identité",
    date: '2026-07-28',
    taille: '2.1 Mo',
    url: '#',
  },
  {
    id: 'doc-004',
    nom: 'BL_MSCU1187.pdf',
    type: 'Bill of Lading',
    date: '2026-08-05',
    taille: '0.5 Mo',
    url: '#',
  },
  {
    id: 'doc-005',
    nom: 'Déclaration_douane.pdf',
    type: 'Douane',
    date: '',
    taille: '—',
    url: '#',
  },
];

// ─── Historique ──────────────────────────────────────────────────────

export const historiqueDossier001: HistoriqueEntry[] = [
  {
    id: 'hist-001',
    date: '2026-07-15T10:30:00',
    action: 'Dossier créé',
    utilisateur: 'Admin',
    details: 'Dossier ouvert suite à la demande du client B. Amrani',
  },
  {
    id: 'hist-002',
    date: '2026-07-16T14:00:00',
    action: 'Statut → Recherche véhicule',
    utilisateur: 'Admin',
    details: 'Recherche de BMW X5 2023 lancée auprès des fournisseurs',
  },
  {
    id: 'hist-003',
    date: '2026-07-20T09:15:00',
    action: 'Véhicule associé',
    utilisateur: 'Ops Chine',
    details: 'BMW X5 2023 (VIN: WBAFG01010L191234) trouvé chez Sino Auto Ltd',
  },
  {
    id: 'hist-004',
    date: '2026-07-22T11:00:00',
    action: 'Statut → Achat confirmé',
    utilisateur: 'Finance',
    details: 'Achat confirmé, paiement fournisseur initié',
  },
  {
    id: 'hist-005',
    date: '2026-07-28T16:30:00',
    action: 'Statut → En mer',
    utilisateur: 'Shipping',
    details: 'Véhicule chargé sur MSC ZONDA, conteneur MSCU-1187-4',
  },
  {
    id: 'hist-006',
    date: '2026-08-01T10:00:00',
    action: 'Contrat signé',
    utilisateur: 'Sales Algérie',
    details: 'Contrat signé par le client, acompte de 1 600 000 DA reçu',
  },
];

// ─── Expéditions ─────────────────────────────────────────────────────

export const expeditions: Expedition[] = [
  {
    id: 'exp-001',
    numero_conteneur: 'MSCU-1187-4',
    navire: 'MSC ZONDA',
    numero_bl: 'MSCUGB123456',
    port_depart: 'Shanghai, CN',
    port_arrivee: 'Alger, DZ',
    etd: '2026-07-28',
    eta: '2026-08-22',
    statut: 'en_mer',
    nombre_vehicules: 3,
    dossier_ids: ['dos-001', 'dos-003'],
  },
  {
    id: 'exp-002',
    numero_conteneur: 'CMAU-4521-7',
    navire: 'CMA CGM MARCO POLO',
    numero_bl: 'CMAUGZ789012',
    port_depart: 'Guangzhou, CN',
    port_arrivee: 'Alger, DZ',
    etd: '2026-08-05',
    eta: '2026-09-01',
    statut: 'en_mer',
    nombre_vehicules: 2,
    dossier_ids: ['dos-004'],
  },
  {
    id: 'exp-003',
    numero_conteneur: 'EGLV-2938-1',
    navire: 'EVERGREEN EVER ACE',
    numero_bl: 'EGLVSH345678',
    port_depart: 'Shanghai, CN',
    port_arrivee: 'Oran, DZ',
    etd: '2026-06-10',
    eta: '2026-07-05',
    statut: 'arrivee',
    nombre_vehicules: 4,
    dossier_ids: ['dos-002'],
  },
  {
    id: 'exp-004',
    numero_conteneur: 'HLXU-7654-3',
    navire: 'HAPAG-LLOYD BERLIN EXPRESS',
    numero_bl: 'HLXUBJ901234',
    port_depart: 'Tianjin, CN',
    port_arrivee: 'Alger, DZ',
    etd: '2026-08-20',
    eta: '2026-09-15',
    statut: 'planifiee',
    nombre_vehicules: 1,
    dossier_ids: ['dos-006'],
  },
  {
    id: 'exp-005',
    numero_conteneur: 'MSKU-3219-8',
    navire: 'MAERSK SEALAND',
    numero_bl: 'MSKUSZ567890',
    port_depart: 'Shenzhen, CN',
    port_arrivee: 'Alger, DZ',
    etd: '2026-05-01',
    eta: '2026-05-28',
    statut: 'dedouanee',
    nombre_vehicules: 2,
    dossier_ids: ['dos-005'],
  },
  {
    id: 'exp-006',
    numero_conteneur: 'TCLU-8472-5',
    navire: 'COSCO SHIPPING ALPS',
    numero_bl: 'TCLUCQ234567',
    port_depart: 'Chongqing, CN',
    port_arrivee: 'Alger, DZ',
    etd: '2026-09-01',
    eta: '2026-09-28',
    statut: 'planifiee',
    nombre_vehicules: 3,
    dossier_ids: [],
  },
];

// ─── Utilisateurs ────────────────────────────────────────────────────

export const utilisateurs: Utilisateur[] = [
  {
    id: 'usr-001',
    nom: 'Djelloul',
    prenom: 'Ahmed',
    email: 'a.djelloul@carimport.dz',
    role: 'super_admin',
    actif: true,
    date_creation: '2025-12-01',
    avatar_initials: 'AD',
  },
  {
    id: 'usr-002',
    nom: 'Mansouri',
    prenom: 'Sara',
    email: 's.mansouri@carimport.dz',
    role: 'sales_algerie',
    actif: true,
    date_creation: '2026-01-10',
    avatar_initials: 'SM',
  },
  {
    id: 'usr-003',
    nom: 'Liu',
    prenom: 'Wei',
    email: 'w.liu@carimport.dz',
    role: 'operations_chine',
    actif: true,
    date_creation: '2026-01-15',
    avatar_initials: 'LW',
  },
  {
    id: 'usr-004',
    nom: 'Boukhris',
    prenom: 'Fatima',
    email: 'f.boukhris@carimport.dz',
    role: 'finance',
    actif: true,
    date_creation: '2026-02-01',
    avatar_initials: 'FB',
  },
  {
    id: 'usr-005',
    nom: 'Rahmani',
    prenom: 'Kamel',
    email: 'k.rahmani@carimport.dz',
    role: 'shipping',
    actif: true,
    date_creation: '2026-02-15',
    avatar_initials: 'KR',
  },
  {
    id: 'usr-006',
    nom: 'Taleb',
    prenom: 'Rachid',
    email: 'r.taleb@carimport.dz',
    role: 'dedouanement',
    actif: false,
    date_creation: '2026-03-01',
    avatar_initials: 'RT',
  },
];

// ─── Dossiers (full detail) ─────────────────────────────────────────

export const dossiers: Dossier[] = [
  {
    id: 'dos-001',
    reference: 'CA-2026-0032',
    client_id: 'cli-001',
    client_nom: 'B. Amrani',
    vehicule_id: 'veh-001',
    vehicule_desc: 'BMW X5 2023',
    fournisseur_nom: 'Sino Auto Ltd',
    statut: 'en_mer',
    origine: 'client',
    date_creation: '2026-07-15',
    date_mise_a_jour: '2026-08-10',
    client: clients[0],
    vehicule: vehicules[0],
    expedition: {
      numero_conteneur: 'MSCU-1187-4',
      navire: 'MSC ZONDA',
      numero_bl: 'MSCUGB123456',
      port_depart: 'Shanghai, CN',
      port_arrivee: 'Alger, DZ',
      etd: '2026-07-28',
      eta: '2026-08-22',
      statut: 'en_mer',
    },
    douane: undefined,
    factures: [factures[0], factures[1], factures[2]],
    documents: documentsDossier001,
    historique: historiqueDossier001,
    contrat_statut: 'signe',
    acompte_recu_dzd: 1600000,
    solde_restant_dzd: 1600000,
  },
  {
    id: 'dos-002',
    reference: 'CA-2026-0018',
    client_id: 'cli-002',
    client_nom: 'K. Benali',
    vehicule_id: 'veh-005',
    vehicule_desc: 'Range Rover Sport 2024',
    fournisseur_nom: 'Golden Star Auto Export',
    statut: 'livre',
    origine: 'client',
    date_creation: '2026-05-10',
    date_mise_a_jour: '2026-07-15',
    client: clients[1],
    vehicule: vehicules[4],
    expedition: {
      numero_conteneur: 'EGLV-2938-1',
      navire: 'EVERGREEN EVER ACE',
      numero_bl: 'EGLVSH345678',
      port_depart: 'Shanghai, CN',
      port_arrivee: 'Oran, DZ',
      etd: '2026-06-10',
      eta: '2026-07-05',
      statut: 'arrivee',
    },
    douane: {
      numero_declaration: 'DD-2026-4521',
      date_declaration: '2026-07-08',
      bureau_douane: 'Bureau Oran Port',
      valeur_declaree_dzd: 11500000,
      droits_douane_dzd: 2300000,
      tva_dzd: 1380000,
      total_frais_dzd: 3680000,
      statut: 'validee',
      date_dedouanement: '2026-07-12',
    },
    factures: [factures[3], factures[4]],
    documents: [],
    historique: [],
    contrat_statut: 'signe',
    acompte_recu_dzd: 2000000,
    solde_restant_dzd: 0,
  },
  {
    id: 'dos-003',
    reference: 'CA-2026-0045',
    client_id: 'cli-003',
    client_nom: 'N. Zerhouni',
    vehicule_id: 'veh-003',
    vehicule_desc: 'Mercedes-Benz GLE 350 2024',
    fournisseur_nom: 'Sino Auto Ltd',
    statut: 'achat_confirme',
    origine: 'client',
    date_creation: '2026-06-25',
    date_mise_a_jour: '2026-08-01',
    client: clients[2],
    vehicule: vehicules[2],
    factures: [factures[5]],
    documents: [],
    historique: [],
    contrat_statut: 'signe',
    acompte_recu_dzd: 3000000,
    solde_restant_dzd: 5900000,
  },
  {
    id: 'dos-004',
    reference: 'CA-2026-0051',
    client_id: 'cli-004',
    client_nom: 'Y. Messaoudi',
    vehicule_id: null,
    vehicule_desc: null,
    fournisseur_nom: null,
    statut: 'recherche_vehicule',
    origine: 'client',
    date_creation: '2026-07-20',
    date_mise_a_jour: '2026-08-05',
    client: clients[3],
    factures: [factures[6]],
    documents: [],
    historique: [],
    contrat_statut: 'signe',
    acompte_recu_dzd: 2500000,
    solde_restant_dzd: 0,
  },
  {
    id: 'dos-005',
    reference: 'CA-2026-0012',
    client_id: 'cli-005',
    client_nom: 'A. Bouzid',
    vehicule_id: 'veh-006',
    vehicule_desc: 'Porsche Cayenne 2024',
    fournisseur_nom: 'Yangtze Auto Group',
    statut: 'cloture',
    origine: 'client',
    date_creation: '2026-03-01',
    date_mise_a_jour: '2026-06-30',
    client: clients[4],
    vehicule: vehicules[5],
    douane: {
      numero_declaration: 'DD-2026-2103',
      date_declaration: '2026-06-01',
      bureau_douane: 'Bureau Alger Port',
      valeur_declaree_dzd: 13900000,
      droits_douane_dzd: 2780000,
      tva_dzd: 1668000,
      total_frais_dzd: 4448000,
      statut: 'validee',
      date_dedouanement: '2026-06-05',
    },
    factures: [],
    documents: [],
    historique: [],
    contrat_statut: 'signe',
    acompte_recu_dzd: 5000000,
    solde_restant_dzd: 0,
  },
  {
    id: 'dos-006',
    reference: 'CA-2026-0058',
    client_id: 'cli-006',
    client_nom: 'M. Khelifi',
    vehicule_id: 'veh-004',
    vehicule_desc: 'Toyota Land Cruiser 2023',
    fournisseur_nom: 'Pacific Vehicle Trading',
    statut: 'douane',
    origine: 'stock',
    date_creation: '2026-08-01',
    date_mise_a_jour: '2026-08-12',
    client: clients[5],
    vehicule: vehicules[3],
    expedition: {
      numero_conteneur: 'HLXU-7654-3',
      navire: 'HAPAG-LLOYD BERLIN EXPRESS',
      numero_bl: 'HLXUBJ901234',
      port_depart: 'Tianjin, CN',
      port_arrivee: 'Alger, DZ',
      etd: '2026-07-15',
      eta: '2026-08-10',
      statut: 'arrivee',
    },
    douane: {
      numero_declaration: 'DD-2026-5892',
      date_declaration: '2026-08-11',
      bureau_douane: 'Bureau Alger Port',
      valeur_declaree_dzd: 10200000,
      droits_douane_dzd: 2040000,
      tva_dzd: 1224000,
      total_frais_dzd: 3264000,
      statut: 'en_cours',
      date_dedouanement: null,
    },
    factures: [],
    documents: [],
    historique: [],
    contrat_statut: 'signe',
    acompte_recu_dzd: 4000000,
    solde_restant_dzd: 6200000,
  },
  {
    id: 'dos-007',
    reference: 'CA-2026-0060',
    client_id: 'cli-001',
    client_nom: 'B. Amrani',
    vehicule_id: 'veh-002',
    vehicule_desc: 'Audi Q7 2024',
    fournisseur_nom: 'Dragon Motors Co.',
    statut: 'nouveau',
    origine: 'stock',
    date_creation: '2026-08-14',
    date_mise_a_jour: '2026-08-14',
    client: clients[0],
    vehicule: vehicules[1],
    factures: [],
    documents: [],
    historique: [],
    contrat_statut: 'brouillon',
    acompte_recu_dzd: 0,
    solde_restant_dzd: 7800000,
  },
];

// ─── Helper: find entities ───────────────────────────────────────────

export function getDossierById(id: string): Dossier | undefined {
  return dossiers.find((d) => d.id === id);
}

export function getClientById(id: string): Client | undefined {
  return clients.find((c) => c.id === id);
}

export function getVehiculeById(id: string): Vehicule | undefined {
  return vehicules.find((v) => v.id === id);
}

export function getFournisseurById(id: string): Fournisseur | undefined {
  return fournisseurs.find((f) => f.id === id);
}
